### ISSUE TITLE
First Thanks you for your great effort

### ISSUE THREAD

**Issue by sajidali2444** [netmedia/angular-architecture-patterns#1]

**Comment by sajidali2444** [comment]
when i try npm run start after pakcages installation this error occured.
npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/Cellar/node/7.10.0/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-architecture-patterns@1.0.0 start: `npm run sy-pre-start & ng serve --proxy-config proxy.conf.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-architecture-patterns@1.0.0 start script 'npm run sy-pre-start & ng serve --proxy-config proxy.conf.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-architecture-patterns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run sy-pre-start & ng serve --proxy-config proxy.conf.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-architecture-patterns
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-architecture-patterns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Sajid/.npm/_logs/2017-05-29T15_10_20_768Z-debug.log

**Comment by anteburazer** [comment]
Hi @sajidali2444 

I use npm v4.2.0 and I tried it with Node v6.9.0 and v7.10.0 on Windows 10 and latest macOS Sierra and everything works normally for me. I believe you have a problem with angular-cli.

Try to uninstall angular-cli globally and locally:

`npm uninstall @angular/cli`
`npm uninstall @angular/cli -g`
`npm cache clean`

And after that install the latest version globally and locally:

`npm install @angular/cli`
`npm install @angular/cli -g`

As I can see you have the latest version of npm (v4.2.0) and node (v7.10.0) so that should be fine.

**Comment by sajidali2444** [comment]
Hi @anteburazer 
Thanks its worked problem was Angular CLI installation.
i am planning to use this architecture in my next project with ASPNET Core.

**Comment by anteburazer** [comment]
I'm glad it fixed the problem. I hope you'll find this architecture useful for your projects.
